package speakit.test.files;

import java.io.File;
import java.io.IOException;

import speakit.TextDocument;

public class TestDocumentRepository {
	public final TextDocument documents[];

	public final TextDocument btree;
	public final TextDocument hamlet;
	public final TextDocument ntfs;
	public final TextDocument unmundofeliz;
	public final TextDocument vulcanizacion;
	public final TextDocument loremipsum;
	public final TextDocument lemario;
	public final TextDocument noname1;
	public final TextDocument noname2;
	public final TextDocument noname3;
	public final TextDocument noname4;
	public final TextDocument noname5;
	public final TextDocument noname6;

	public TestDocumentRepository() throws IOException {
		btree = new TextDocument(1, new File("src/speakit/test/files/btree.txt"), true);
		hamlet = new TextDocument(1, new File("src/speakit/test/files/hamlet.txt"), true);
		ntfs = new TextDocument(1, new File("src/speakit/test/files/ntfs.txt"), true);
		unmundofeliz = new TextDocument(1, new File("src/speakit/test/files/unmundofeliz.txt"), true);
		vulcanizacion = new TextDocument(1, new File("src/speakit/test/files/vulcanizacion.txt"), true);
		loremipsum = new TextDocument(1, new File("src/speakit/test/files/loremipsum.txt"), true);
		lemario = new TextDocument(1, new File("src/speakit/test/files/lemario.txt"), true);
		noname1 = new TextDocument(1, longText1, true);
		noname2 = new TextDocument(1, longText2, true);
		noname3 = new TextDocument(1, longText3, true);
		noname4 = new TextDocument(1, longText4, true);
		noname5 = new TextDocument(1, longText5, true);
		noname6 = new TextDocument(1, longText6, true);

		//documents = new TextDocument[] { btree, hamlet, ntfs, unmundofeliz, vulcanizacion, loremipsum, lemario, noname1, noname2, noname3, noname4, noname5, noname6 };
		documents = new TextDocument[] { btree, hamlet, ntfs, unmundofeliz, vulcanizacion, loremipsum, noname1, noname2, noname3, noname4, noname5, noname6 };
	}

	String longText1 = "Libro no, guión cinematográfico no, obra de tratro no, todo no, todo no, todo no. Billones y billones de usuarios me escriben explicándome que han intentado toda la gama de los géneros literarios siguiendo mis consejos y han fracasado miserablemente, exigiéndome por tanto la devolución del importe de los talleres más un “plus” por “lucro cesante”, que es como que te tengo que pagar por ser un inoperante."
			+ "Lamentable la política de la empresa incluye, grabada a fuego, una “cláusula de no devolución de dinero y en general de ninguna otra cosa”, por lo que no va a poder ser, querido. En vez, les ofrezco –a mitad de precio- una clase especial develando los secretos del género literario más menospreciado de todos: el arte de la conversación. Si ud. domina este género, no va a poder lucrar con él pero le facilitará hacer contactos. Tender los hilos, hacer negocios, relaciones públicas, todas esas cositas que luego lo habilitarán para su primer libro o puesto en presidencia de la Nación. Si alcanza un nivel de conversación aceptable, tal vez alguien incluso se atreva a publicar un libro de “Conversaciones con (inserte aquí su nombre)” y ahí capaz le puede pedir plata. Por fin, dominar el arte de la Conversación tal vez lo acredite para ser invitado a un programa o a un panel de algo, aunque mis magras experiencias en el ramo no me han reportado ganancia alguna. Pero de golpe ahí tenés a Winograd o a Jorge Asís que nadie sabe qué hacen pero, cómo hablan, mamita querida, y me refiero sobre todo a la cantidad."
			+ "Empecemos por el hecho de que la gente no sabe hablar. El arte de la conversación ha muerto o está agonizando básicamente por ausencia de capacidad de hilación de dos frases seguidas en el humano promedio. El locuaz polemista cibernético, que puede deshacerse en largas parrafadas en el espacio virtual, no es capaz de sobrepasar el nivel del borborigmo inarticulado en la vida real."
			+ "El conversador promedio actual se pierde en medio de las oraciones, hace ruidos con saliva, confunde los tiempos verbales (con otros tiempos verbales pero incluso con sustantivos o cosas), es incapaz de describir algo, repite el mismo adjetivo para definir todo, interrumpe, no es capaz de relacionar un hecho “a” con un hecho “b”, carece de anécdotas personales o ajenas, cree que el idioma es una herramienta y no un juego de mesa, dice cosas que escuchó en la tele, se detiene en medio de una historia dieciocho veces para autocorregirse insignificantes detalles de la misma y por fin todos sus esfuerzos de participación en la charla se dirigen a mechar el hecho de que se compró tal o cual aparatito. En resumen, un bodrio."
			+ "Esto es obviamente culpa de la tele, lo internet y los jueguitos, pero también del desconocimiento básico de algunas herramientas básicas que los grandes conversadores de antaño dominaban a la perfección. Repasemos algunas:"
			+ "LOS VERSITOS: Cualquiera que haya conversado con un padre, un abuelo o un suegro sabe que esta clase de gente no puede pasar dos minutos de charla sin que algo le recuerde tal o cual versito. Puede ser el fragmento de una canción, de un poema escrito por uno de los grandes Maestros de la Poesía o sencillamente de un versito que leyó alguna vez en un cartelito de un almacén. Este elemento le aporta a la conversación algo más que el intercambio de anécdotas aburridas u opiniones bodrias. Le aporta musicalidad y zucundún, zucundún. Una conversación sin versitos es como un plato de arroz sin queso rallado. No necesariamente deben ser piezas en verso: un refrán desconocido o una frase célebre (acompañada del nombre de su autor) también pueden servir de adorno."
			+ "Por supuesto que lo más complicado es encontrar el versito justo para meterlo en el momento pertinente de la conversación. Por eso, el aspirante a conversador debe aprenderse todos los días entre diez y veinte versitos y memorizarlos, esperando que llegue la ocasión adecuada. Si este no llega, el versito hay que meterlo igual. La gente se sentirá desconcertada pero lo agradecerá."
			+ "Ejemplo:"
			+ "-Qué bárbaro, ya estamos en mayo."
			+ "-Como en el “Romance del Prisionero”: “Que por mayo era por mayo, cuando hace la calor, cuando canta la calandria, y están los campos en flor”."
			+ "De ahí se puede derivar a temas como la situación de los presos en la Argentina, la ornitología, poesía española y por supuesto a lo de qué loco, mayo y todavía hace calor."
			+ "LA ÉPOCA DE PERÓN: Un elemento a tener en cuenta en el Arte de la Conversación es cómo iniciar una anécdota, relato o ejemplo histórico. Encuentro que, por algún motivo, la época de Perón es un buen “leit-motiv” que captura inmediatamente la atención del contrincante. Las frases para iniciar la historia pueden ser, por ejemplo “Cuando subió Perón en el 45…” o “Me acuerdo allá por el 55…” o “Cuando volvió Perón en el 73…”, etc. El resto de la historia va por cuenta del conversador. Puede estar o no relacionado vagamente con Perón. No importa. Lo importante es que ha empezado la frase y se ha vencido el “temor a la hoja en blanco”. Otras posibles frases son “Cuando estuve en la Acrópolis…” o “La vez que por poco no cuento el cuento fue cuando…”"
			+ "Frases no recomendadas para iniciar una frase: “El otro día vi en la tele que…”, “Mi chica/o dice que…”, “Me llegó un mail que dice que…”, “¿Sabés cuánto me salió el…?”, “El otro día me salió un grano en el…”, “Cuando me operaron de la…”, “Una vez me hice popó y eso que tenía 40 años, resulta que…”, “Si hablamos de asquerosidades, en Youtube pusieron un coso donde…” y “A ver”."
			+ "Ejemplo:"
			+ "-Qué calor que hace, ¿eh?"
			+ "-En la Época de Perón, ahí en el 17 de octubre, parece que también hacía bastante calor, te acordás de cómo los tipos se mojaban las patas en la fuente. Bueno, un poroto al lado de esto."
			+ "LOS NÚMEROS DE LA QUINIELA: Otro elemento muy enriquecedor que suelen utilizar nuestros mayores es la lista de números de la quiniela y sus sueños correspondientes. Es muy útil como “parante” o “apoyo” del parlamento del contrincante cuando este es muy bodrio y de paso sirve para hacerle recordar de nuestra presencia (y de paso que agilice un poco)."
			+ "Para poder aplicar esta herramienta, claro, hay que memorizar los números de la quiniela (en tres meses un ser humano normal puede lograrlo) y tenerlos en la punta de la lengua, como para utilizarlos en cuanto el otro conversador mencione un número. De no ser así, pueden inventarse números de la quiniela imaginarios y confiar que el otro tipo no los conozca."
			+ "Ejemplo:"
			+ "-Y me dijeron que tardaban en reconectártelo como 36 horas."
			+ "-36, el Vampiro. ¡Qué barbaridad!"
			+ "Tengo que decir que no saber los números de la quineila de memoria es una de mis grandes frustraciones. Si pudiera, estaría haciendo esto todo el tiempo."
			+ "LOS OJOS: El buen conversador utiliza tanto las palabras, los versitos, la época de Perón y los números de la Quiniela como los ojos. Para empezar, debemos recordar que cuando el conversador se convierte en oyente debe mirar al conversador “b”. Desgraciadamente la vida moderna hace que muchas de nuestras conversaciones se produzcan entre tipos que están mirando una pantallita como estúpidos. Claro que así les salen. Malísimas. Sin embargo, de no mediar computadora se puede considerar una grosería mirar para otro lado cuando alguien nos habla, actitud que puede impulsar el completo fracaso de la conversación. El oyente debe “salpimentar” el relato ajeno con aperturas de párpados, abriéndolos en diferentes tamaños para indicar los diferentes niveles de asombro o cerrándolos (con un leve asentimiento en “cámara lenta” de la cabeza) al final de la historia, como diciendo “Claro, qué bárbaro, no, tenés razón”. Los ojos juegan un rol aún más importante en el conversador activo, acompañando el “acting” de los diversos personajes de la anécdota, mirando al oyente sin penetrarlo con los ojos, sino focalizando la vista en una zona indefinida de su rostro, posando la vista alternativamente en los diversos oyentes si son más de uno y cerrándolos en la conclusión final, como bajando el telón."
			+ "Ejemplo: ...La cosa es que al final llegamos y el perro se lo había comido (cierra los ojos)"
			+ "EL SILENCIO: La conversación es un arte en colaboración. Si una persona es conversadora y la otra no, entonces estamos ante el caso de un “Monólogo” y eso ya es más jodido porque parece que hay que verlo en un teatro y pagarlo. Por eso el conversador debe apelar a todos los medos posibles para que la participación del enemigo también sea significativa."
			+ "Por eso el manejo del silencio es importantísimo, ya que quieren las reglas de la cponversación y hasta diría de la física del oído y el cerebro humanos que mientras uno habla, el otro se calle. Esto, que parece tan sencillo porque simplemente no hay que hacer algo, es menospreciado en la mayoría de las conversaciones, que suelen parecerse más a un duelo a los cachetazos que a un baile sobre patines de hielo."
			+ "Por otro lado, el silencio sirve también para ir preparando uno la contrarréplica o contraanécdota, redactarla mentalmente y agregarle versitos y números de quiniela. Por supuesto, no olvide abrir y cerrar los ojos, para que el tipo siga con la ilusión de que ud. lo escucha. Por fin, cuando el hombre ha terminado de hablar, recuerde que es necesario dejar una pequeña pausa, como un “colchoncito” para que no parezca que ud. está completamente desesperado por intervenir. Este ejercicio de paciencia tiene un doble premio: por un lado, el aire embellecerá un poco su obra, es decir la conversación ( y no parecerá unn guiso de lentejas), y por otro lado el otro tipo se sentirá obligado a hacer silencio. Por supuesto, lo cortés no quita lo valiente, y si a pesar de su esfuerzo el contrario lo interrumpe más de dos veces (la Momia), ud. puede recurrir a la violencia para acallarlo."
			+ "Ejemplo:" + "-…" + "LOS TEMAS: Evite a toda costa los siguientes temas, capaces de embodriar las conversaciones más prometedoras:" + "-Cosas de computación y cosas para hacer que las máquinas anden mejor, o cosas que hay que comprarse para la cosa de la computación y los precios de las diferentes cosas esas." + "-Remedios para diferentes cosas y cuánto salen." + "-Programas de cable y de qué se tratan y cuándo los dan." + "-El clima, especialmente el calor."
			+ "-Lo del campo y lo del gobierno." + "-Modelos de autos modernos y cuánto salen y por qué te conviene comprarte un auto así o un auto asá." + "-Trámites de títulos y cuándo te dijeron que te los iban adar." + "-Enfermedades de niños." + "-La Educación argentina y lo que hay que hacer para arreglar la Educación argentina y por qué anda así la Educación argentina."
			+ "-Modelos de teléfonos celulares y cosas para ponerles para que anden mejor y cuántos alen las cosas esas y los celulares propiamente dicho y cuánto hay que pagar para que te den el servicio ese de que anda el celular." + "-Refacciones de casas y cuánto tardaron en hacerte la refacción de la casa y cuánto te salió y las próximas refacciones que querés hacer en la casa y cuánto sale y cómo pensás pagarla." + "-Dietas especiales."
			+ "El resto de los temas son válidos: La aeronáutica, los recuerdos del Colegio, los animales, el Renacimiento, el canibalismo, recetas de cocina, Popeye, las colonias jesuíticas, la invisibilidad, lo que dijo Mario Mactas, anécdotas de vecinos medio loquibambis, borracheras, los niños, historias de caídas al piso, expresiones idiomáticas, etc. Un buen conversador debe intentar en lo posible desviar los temas bodrios a los temas no bodrios." + "Ejemplo:"
			+ "-Lo que vos tenés que hacer es pedirle a tu técnico que te traiga un disco de rebuteo y entonces que te lo ponga y así esos archivos se te van a hacer visibles." + "-Ah, la visibilidad, qué tema, aunque no tan controvertido como la invisibilidad. A propósito, ¿qué te parece la invisibilidad? Yo preferiría volar. O ser caníbal, no sé."
			+ "EL VINO: Por fin, si los conversadores son especialmente ineptos se recomienda fervientemente que haya vino. Si son competentes, también. Se recomienda a los educandos que graben la conversación resultante para poder estudiarla a posteriori. Bueno, y también para revisar que uno no haya dicho algo indebido o que haya denunciado a alguien al FBI a manera de broma, o que haya prometido pasear al perro completamente desnudo";

	String longText2 = " Dengos: ¿Nueva tendencia o moda pasajera?"
			+ "“Mmmmmbbbb, mmmbbb, mbbmbmmmbbmmm”, dice Jaqueline (27), detrás de su máscara de oxígeno, instalada sobre su capucha de látex a su vez enfundada sobre el triple vendaje untado en repelente. Y es que, como todos los miembros de la movida “Dengo”, debe luchar contra la incomprensión de la sociedad tanto como contra la incomprensión meramente auditiva."
			+ "Mientras las autoridades metropolitanas hacen todo lo que está en sus manos para detener el avance del dengue –que consiste básicamente, confiar en que el Aedes Aegypty llegue hasta la General Paz, se sienta intimidado por la arrolladora personalidad de los porteños y ahí pegue la media vuelta-, la población de Buenos Aires ha realizado creativamente como siempre lo hace en momentos de crisis: inventando una nueva “tribu urbana”."
			+ "“Para mí, ser un ‘dengo’ es más que una moda: es una filosofía de vida”, dice Martín (21), un joven “dengo” que ha aprendido a modular exageradamente y gritar –tipo Gustavo Cerati- para que sus interlocutores lo entiendan, incluso bajo la triple capa protectiva de materiales elastizados que recubren su persona. “Cuando empezó esta movida, parecía que se trataba solo de gente medio aterrorizada que insistía en que había que usar manga larga, dar vuelta recipientes al aire libre y embadurnarse con repelente. Pero un montón de nosotros pensamos que eso podía dar lugar a algo más copado”. Martín se interrumpe para untar la totalidad de la superficie de su mameluco de látex con una capa de 3 cm. de “Off”, ceremonia que los “dengos” realizan cada cinco minutos. Cuando termina, me ofrece una pastillita de Fuyi Vape, y ante mi negativa se abre una puertita del casco que cubre su cabeza y se la manduca, sin agua ni nada. ¿Y no le hace mal? “Un poco. Por ejemplo, ya perdí la capacidad de distinguir los contornos de las cosas. Y un poco la parte de adentro también. ¡Pero siempre va a ser mejor que tomar aspirinas!”, grita, con furia (Los “dengos” odian la aspirina y estiman que quienes la consumen son unos “negros cabeza”)."
			+ "“La guerra de Vietnam impulsó el movimiento hippie, y el desempleo británico dio origen al punk”, dice Amadeo Rosenwasser (56), sociólogo. “A nosotros, la aparición del dengue nos ha dejado toda una subcultura. Lo más sorprendente es la velocidad con que se ha extendido: a las tres horas de conocerse los primeros casos en Charata, en Internet ya había más de 456.78e7.334.9896.000.000.90 páginas dedicadas al ‘Movimiento Dengo’. La verdad es que la gente no es más pelotuda porque no tiene tiempo”, agrega, en un tono muy académico."
			+ "Por si la masividad del Movimiento “Dengo” es puesta en duda, las ventas de vestuario y máscaras de látex en Sex Shops fetichistas, tiendas de disfraces y convenciones de cómic –que ya se reveló que es todo lo mismo- se han cuadriplicado, casi exclusivamente en artículos que aíslen la piel del ataque del mosquito. “Me piden de todo, desde bolsas marineras tipo 'Audition' a disfraces de Batman”, dice Mario (49), dueño de local “Bebota, esta carne es para vos” sito en una galería de Florida. “Incluso se agotaron unas caretas de De la Rúa que me llegaron por error.”"
			+ "Pero, ¿qué es realmente ser un “dengo”? ¿Cuál es su ideal último, si es que este corpus de rituales sin sentido para el lego tiene un fin último? “La total y absoluta aislación (sic) corporal y mental de cualquier tipo de contacto con el exterior, para conseguir un estado superior de conciencia, una sanidad física total y una pureza de cuerpo y espíritu y aparte no tener dengue”, dice con voz apasionada Princess Nefertiti (17), gurú del Movimiento “Dengo” y autora del blog “No me moleste mosquito”, que recibe aproximadamente 234.5678.90.0.876.321.000 visitas por día, aunque diez de ellas por parte de surfeadores accidentales (hay que decir que dice “sexo gratis” en el header)."
			+ "Princess Nefertiti se ufana de ser una de las “dengos” con más capas de cosas entre su epidermis y el exterior. “Tengo unas 17 capas, entre enteritos de látex, goma y ropa de distintos talles. Entre capa y capa me embadurno toda con Off y pastillitas Fuyí Vape picadas. Tardo unas tres horas en vestirme, y otras dos horas en ponerme las capas para dormir bajo mi mosquitero hecho con bolsas de residuos.” A pesar de su aspecto exterior (lleva una máscara de Domingo Cavallo y la superposición de ropajes le da el aspecto de una piñata humana), comentarios como “¡Diosa!” o “¡Te como toda!” son frecuentes en su blog."
			+ "“Me puse Princess Nefertiti, que es un nombre egipcio, como el mosquito”, nos aclara la Reina de los “dengos” mientras nos guía hasta un estacionamiento subterráneo abandonado (los miembros de esta tribu odian el aire libre, por ser caldo de cultivo de “esos bichos de mierda que te pican y te morís”, según Princess Nefertiti) donde se realiza el “XVIII Encuentro Alternativo Dengo”, que se realiza cada seis horas, y donde los “dengos” comparten secretos, escuchan su música, celebran orgías de embadurnamiento con Off, se ponen hasta las cejas de tabletas Fuyí y comercian artículos que reflejan su subcultura. “Me compré esto por 45 mangos”, nos dice Laura (16), una joven “dengo” envuelta en un mameluco anaranjado, mientras nos muestra un par de aros confeccionados con espirales (que, como todos saben, se hacen con bosta de vaca). Luego de encenderlos, aclara “Igual para dormir me los saco, obvio”. Desde el interior de un antiguo arcón de madera cubierto de cadenas y cerrojos, Demián (20) nos dice “Para mí al Movimiento ‘Dengo’ se lo está fagocitando el sistema. Ya no es lo que era cuando nació, la semana pasada. Por eso yo curto el ‘Denguismo Extremo’ desde adentro de este baúl. Lo único que estoy empezando a tener un poco de hambre.”"
			+ "¿Moda? ¿Movimiento? ¿Locura? ¿Invento de los medios? Mientras Princess Nefertiti sube al estrado y es ovacionada por sus admiradores, la verdadera “fiesta dengo” arranca, y los asistentes empiezan a patear recipientes –baldes, ollas, neumáticos- colocados estratégicamente a lo alrgo del predio, con el objeto de darlos vuelta. Entonces, una mariposa desorientada ingresa al estacionamiento, alguien la señala al grito de “¡Dengue!” y la multitud se dispersa entre patadas, atropellamientos y uno o dos muertos aplastados."
			+ "Moda pasajera o no, los “dengos” están aquí para quedarse.";

	String longText3 = " ¿Qué me mirás sin esa cara?"
			+ "Durante décadas, los pesimistas gurúes de la ciencia ficción han alertado a la Humanidad sobre los peligros del confort: Desde “Los Supersónicos”, y a la película “Wall-E”, pasando por la historieta de Kurtzman y Wood “Blobs!” (en los inicios de la revista “Mad”) nos han mostrado un futuro donde el uso de la tecnología ha convertido al Hombre en un bebé absolutamente dependiente y con el cuerpo completamente fofo y atrofiado, culpa de las veredas móviles y mini-transportes individuales."
			+ "Sin embargo, ninguno de estos Nostradamus de pacotilla fue capaz de predecir la peor consecuencia de la tecnología, y que –es hora de revelarlo- está ocurriendo en este momento: Se nos está atrofiando la cara."
			+ "Antaño, cuando la forma de comunicación humana más extendida era cara a cara, el lenguaje oral estaba acompañado por miles y miles de pequeños gestos, visajes, guiños, inflexiones en la voz, miradas y muecas que complementaban el limitadísimo sistema de comunicación verbal. Entonces, gracias a este conjunto de herramientas periféricas de la palabra, fue el reino del sarcasmo. Uno podía decir “ah, sí, los comentaristas de blogs, esos sí que son re grosos”, y gracias a una mirada, un gesto realizado con los dientes superiores o cierta anomalía autoinflingida en la voz, el interlocutor podía dilucidar el verdadero significado. Este arte fue tomando ramas cada vez más sutiles, una sencilla levantada de ceja podía eliminar de un plumazo todo lo que el sarcástico de turno acababa de decir."
			+ "Hoy en día, cuando las jóvenes generaciones (y cuando digo joven, digo “joven” en serio, tipo 17 años para abajo, no lo que los medios periodísticos consideran un “escritor joven” o un “director joven”, juventud muy elástica que puede extenderse hasta los sesenta años) quieren borrar con el codo lo que dicen con la mano, dicen “arre”. Por ejemplo, agarran y dicen “Los comentaristas de blogs, esos sí que son grosos. Arre”. Esta palabrita, “arre”, funciona de reemplazo a esa catarata de información gestual y vocal de la que hablaba al principio. De sostenerse en el tiempo, hará completamente innecesaria la realización de muecas, y por fin, seremos tan expresivos como un escandinavo."
			+ "No seamos muy duros con los jóvenes: la palabra “arre” es un idiotismo derivado del “lenguaje flogger” (según una breve investigación, su etimología viene, viene de “ahh, re que no”), donde justamente se utizaba originalmente como “warning de sarcasmo”, para evitar malentendidos."
			+ "¿No les recuerda (y tal vez les despierte cierta envidia por la practicidad del adminículo) a las constantes ofensas inintencionadas, bodrios intercambios de aclaraciones, disculpas, “yo no quise decir lo que dije” y “yo no dije que vos hayas querido decir lo que vos dijiste sino todo lo contrario” que solemos leer y experimentar en blogs y foros de gente mayor? Desde luego, los adultos no estamos a salvo de la incómoda inexpresividad de nuestro medio. Pocas cosas hay tan escalofriantes como nuestros “jajaja” escritos con un rostro absolutamente pétreo e inexpresivo; no necesitamos expresar simpatía, odio, celos, alegría, ternura, malicia ni amarga indiferencia hacia el interlocutor que está detrás de la pantalla del monitor. Y quiere la Naturaleza Humana que cuando no necesitamos hacer algo, no lo hacemos. Así que expresamos nuestros peores instintos y mejores deseos a través de la escritura, pero con una cara de leer avisos clasificados que no le hace el más mínimo honor a estos humanos sentimientos."
			+ "El problema es que, así como nuestra carencia de herramientas idiomáticas floggers nos mantiene toscos en la conversación cibernética, nuestros jóvenes simétricamente han empezado a utilizar esta suerte de emoticones en el habla cotidiana; ¿en cuántas generaciones el “habla emoticona” dejará sin capacidad de expresión gestual a la raza humana? ¿Llegaremos a vivir en un mundo liso y rosa, donde los seres humanos no pueden poner “cara de Robert de Niro”, abrir las aletas de la nariz en señal de ira contenida o elevar una ceja demsotrando desconfianza? ¿Desaparecerán las patas de gallo y “líneas de expresión”, dándonos aspecto de bebés monstruosos y encanecidos?"
			+ "En ese mundo, los hombres hablarán de nosotros como de esos Superhombres capaces de hazañas increíbles, como fruncir la nariz o ponernos bizcos. Jim Carrey será para ellos una suerte de Dios (incluso creerán que la película “Todopoderoso” es un documental) e Ismael Echeverría, su profeta. Desde luego, el gesto facial como demostración de afecto desaparecerá por completo, perdiendo la actividad erótica un 76 % de atractivo y reduciendo la tasa de natalidad, y el amor volverá a expresarse por la espalda como en la era de las cavernas. Desaparecida la risa (reemplazada por un “he encontrado eso muy gracioso” expresado verbalmente), también desaparecerán los cómicos stand-up, ya que los chistes sin un ruido que los acompañe colapsan sobre sí mismos. Por último, sin el ejercicio de los músculos faciales la tonicidad muscular de las caras de nuestros bisnietos desaparecerá a los 25 años de edad, con el consiguiente peligro de desprendimiento de nariz, etc."
			+ "La única forma de evitar esto es exigir que la escuela pública incorpore “Expresividad Facial” como materia O-BLI-GA-TO-RIA, donde se les enseñe a los educandos a bajar el extremo central de las cejas para denotar enojo, hacer una boquita tipo Francella para expresar temor, y otros. Eso, o que se empiecen a fabricar caretas con distintas expresiones, que todo el mundo tenga a mano para las diferentes ocasiones. No sé, esto también estaría bueno, aparte si querés enojarte mucho te podés poner una cara de Mr. T.";

	String longText4 = " ¡Proponen –ellos– unos programas metafísicos de TV!"
			+ "Entendemos que las nuevas tecnologías (microcámaras capaces de meterse dentro de las arterias humanas, edición digital, cámaras infrarrojas, cámaras que tiran vision calórica, etc.) no están aprovechadas a full, al máximo, al 100 %. Por eso “Yo contra el Mundo” propone los siguientes “programas de televisión metafísicos”:"
			+ "360 °: Se trata de una serie de ficción al estilo de “24 horas”, pero en lugar de seguir las peripecias del protagonista segundo a segundo, se toma un segundo en la vida del protagonista y se ve todo lo que está pasando a su alrededor. Nos referimos a todo su alrededor, es decir, al mundo. Por ejemplo: El protagonista está en una terraza, apuntando con un rifle al Presidente de los Estados Unidos. La imagen se congela y empezamos a alejarnos del tipo en leve movimiento espiralado: Se ve al propio Presidente, a sus ministros, a la multitud que lo ovaciona o abuchea, luego al verdulero que está en la otra uadra, también al carnicero, y al peluquero y al ferretero y al boticario la señora que tiene una dietética, y a la gente que vive en el edificio donde están instalados esos comercios, visitando departamento por departamento a todos y cada uno de los inquilinos, a la Sra. Tincasetti, al matrimonio Ochmoneck, a los Brady y a los O’Malley. Luego vamos al edificio de enfrente y vemos al Sr. González, a la Sra. Rachmaninoff, a la familia Mulligan y a los Corleone. Luego pasamos a los barrios vecinos, a visitar cada uno de los departamentos de los edificios de las calles de esos barrios. Vemos el departamento del Sr. Muchnick, de la familia Pérez y de los ortega y los Rabufetti y los Ostertag. Sí, sí, a los Frumdiltong también. Y también a los O’ Franganngangan y a los Schortknijyyytcknik y a los Wilamssumburgomgurgurgurg también, y a los Bopprenheimerrerr y los Tyonghiu y los Prrrohumghui y los Blogrodbtopp. A todos. Luego vamso a las ciudades vecinas. Bueno, y así."
			+ "Como el factor que estamos cubriendo es el espacio y no el tiempo, el programa debería tener una duración temporal de cero. Pero sabemos que esto es imposible, debido a los códigos de la televisión. Así que proponemos que dure un segundo. ¿Cómo? Gracias a la magia de la cámara rápida (la tecnología digital moderna ha hecho posible gracias a unas cpamras rápidas muy muy rápidas). La ventaja de esta duración es que permite que el programa tenga mucha publicidad, aumentando las ganancias un 78.64.995649 %%%%% por ciento."
			+ "“¡QUÉ GRACIOSO ES ESTO!”: Se trata de uno de esos programas humorísticos con público en vivo, donde cada tanto enfocan a la gente riendo o sonriéndose o aplaudiendo. La diferencia es que en este programa, sólo se muestra eso. A la gente riéndose. Mediante un sofisticado sistema de audio que incluye un botocito de “off”, no se nos permite escuchar lo que dicen los protagonsitas del programa, sino solamente las risas. El resultado es un “viaje” tragicómico y angustiante, en el que, como los habitantes de la caverna de Platón, no vemos la luz sino las sombras que ésta produce, o algo así (no recuerdo cómo era exactamente. Tampoco recuerdo si era Platón. Esto es televisión, amigos). No vemos lo que produce la risa, sino sus resultados, y durante una horita minutos más minutos menos, nos sentimos angustiadísimos, pensando en lo que nos estaremos perdiendo. Porque además, uno de los requisitos es que que el programa –el que no vemos- sea buenísimo, como para que la gente se haga encima de la risa sin parar. De cualquier modo, lo más probable es que, por un fenómeno de simpatía o tal vez histeria, nos terminemos riendo igual (también hay grandes probabilidades de que éste se convierta en uno de esos programas recomendados por drogones, esos de que “uh, ayer me clavé un faso y me vi ‘¡Qué gracioso es esto!’, no sabés”). El programa se financia, justamente, con la venta de droga."
			+ "“MY TRUE LIFE”: Se trata de uno de esos realities donde vemos 24 horas en la vida de alguien a través, con una camarita pegada con la Gotita en la frente, o cosida en las córneas, o con unostacos fischer y unos tornillos de media pulgada en el tabique de la nariz. O algún otro método menos cruento, si es que algún día existe esa tecnología. La cosa es que en este caso, la vida de la persona elegida es la de usted. Entonces pasa todo el día con el aparatito ese en los ojos, y se graba cómo desayuna, cómo se ducha (se le pide que se envuelva la camarita con una bolsa de Coto), cómo se toma el colectivo, cómo pasa ocho horitas fente a la computadora chateando y escribiendo pelotudeces y viendo cosas en Youtube, cómo vuelve a su casa, cómo cena, cómo se lava los dientes y cómo se queda dormido viendo “Constantine”, y luego despierta en mitad de la noche confuso y sudado. Una vez terminada de editar esta grabación (se le arreglan un par de cositas de audio), al día siguiente se le entrega el programa (en un DVD, o un cassette) para que lo vea exclusivamente usted. Entero. Por segunda vez. O sea, pasa las 24 horas del día siguiente, viendo exactamente todo lo que vio a través de sus propios ojos el día anterior. Hay que aclarar que cada programa viene acompañado de unas pildoritas de cianuro. ";

	String longText5 = " ¡Denuncian plan yanqui de “obamización” de la Argentina!"
			+ "DÍA 1 DEL “COMPROMISO PODETI”"
			+ "Por razones de fuerza mayor, el “Compromiso Podeti” –un larguito todos los días- se pospone por el día de la fecha. La razón es que me ha llegado un mail bastante largo pero que me ha dejado un poco preocupado por las cponsecuencias que puede tener para el destino de nuestro país. Lo transcribo –se me rompió la tecla de “copy paste”, así que lo tipeo de vuelta- para que juzguen por ustedes mismos:"
			+ "Por favor reenvíen este mail a todas sus direcciones. Está en juego el futuro de todos nosotros y del lugar que le queremos dejar a nuestros hijos y del mundo en general. No sé si esto es una broma o no pero por las dudas lo paso total si es una broma después nos reímos todos pero no es una broma, mándenlo porque los medios lo están ocultando y esto SE TIENE QUE SABER."
			+ "Una periodista muy conocida entre sus allegados cercana auna importante fuente relacionada con una embajada de un país aliado a una agencia de noticias muy cercana a un conocido funcionario del Gobierno ha comentado entre bambalinas ciertas noticias que tienen que ver con el tema de que es mayo y hacen 35 grados a la sombra."
			+ "La temperatura tendría que ver con la estrategia que estaría siguiendo el Gobierno para enfrentar la crisis del Dengue en nuestro país (ahora que se descubrió que lo de la gripe porcina, creada para que se coma al virus del dengue era un bluff), y que consistiría en que los miembros del statu quo kirchnerista estarían esperando –pero esperando con mucho mucho fervor y entusiasmo- que venga el otoño de una buena vez por todas y arrase con el Aedes Aegpty. Este plan –el de esperar- habría calado hondo en la estrategia comunicacional del Gobierno, que se sentiría identificado con la Rusia Soviética de la II Guerra Mundial por lo de contar como “carta fuerte” con el “General Invierno” en sus intentos por detener a Hitler."
			+ "Gracias a esta inspiración el Kirchenrismo relanzaría el Gobierno de la Presidente Cristina Fernández como una Dictadura “Neo Estalinista” (Bajo el lema de “tanto tanto rompeiron las pelotas de que somos autoritarios, bueno, acá está, ahora somos estaliniatas, ¿qué tul?”), claro que sin genocidios que quedan medio feos y son caros de implementar, ni dictadura del proletariado ni reforma agraria ni comisarios del pueblo que es todo medio difícil, sino Estalinistas desde el hecho de decir que son Estalinistas y hacer pósters con estética constructivista. Como contrapartida, se alzaría contra el Gobierno un sector trostskista del kirchenrismo aduciendo que “mejor que siga haciendo calor, así la gente gasta menos guita en gas y está de buen humor”, estrategia que sería discutida en el Politburó con el argumento dialéctico de que “pero el calor también te pone de vuen humor”, rebatido a su vez por algunos teóricos del materialismo histórico con que “y, pero no sé”, a lo que seguirían las tesis marxistas de que “yo te prefiero el frío al calor toda la vida”, “y, pero y la gente que no tiene casa, preguntale a esa si quiere que venga el invierno”, “ah, bueeeeeeno”, “no sé, no sé”, “qué se yo”, “y buéh”, “puede ser”, “y, es todo según” e “igual es todo una mierda”."
			+ "Instalado el Estalinismo en nuestro país se revelaría la cara oculta del plan, lanzada por la agenda secreta de los republicanos de la Casa Blanca de Bush de Obama para reinstalar la “Guerra Fría” –lo que coincidiría con el tema del invierno-, sólo que en lugar de promoverla de oeste a este que es medio bodrio porque te agarra el “jet lag” se realizaría de norte a sur “que aparte los monitos estos del Sur son menos jodidos que los rusos”, como habría argumentado la Secretaria de Estado Hillary Clinton. Reinstalada la Guerra Fría, se revitalizaría la fabricación ya no de misiles –lo que iría en contra del paulatino proceso de desarme nuclear programado para el año 23.678- sino de pinzas pico de loro gigantes para hacer girar las plataformas de misiles y que apunten para este lado, con la consecuente revitalización de la indistria siderúrgica."
			+ "Con este fin, los testaferros de la CIA Benetton, Robert Duvall y Douglas Thompkins habría comprado 20.000 kilómetros de territorio argentino pegaditos a la cordillera, a donde se habrían instalado enormes estufas –colocados sobre la Cordillera justamente para que sean de tiro balanceado- gracias a las cuales estarían extendiendo este Verano Eterno hasta los límites que hoy sufren miles de compatriotas."
			+ "Como plus, esta estrategia de “Calefacción Regional” apuntaría a terminar de romper el Glaciar Perito Moreno, que no se rompe más y ya mjedio que cansó, y de paso eliminar de un plumazo el turismo del principal “Feudo K.”, lo que llevaría la cadena de Hoteles Kirchner a la ruina. De este modo la agenda del Pentágono de los Halcones Demócratas de George W. Bysh de Barak Obama buscarían crear un a “glasznost” y una “perestroika” dentro de la estalinización kircherista, buscando el ascenso del empresario Francisco De Narváez, que sería presentado como el “Obama Sudamericano” en su rol de representante de una etnia discriminada (los pelirrojos) y crear el contexto para una obamización de la política argentina, conocida como denarvaezisación. Se vivirá una euforia de reivindicación “colorada” y veremos spots publicitarios de pelirrojos famosos (por ejemplo, el jugador McAllister) llorando y diciendo “nunca creí que llegaría este momento”. Se aprovechará toda esta confusión para que el nuevo Gobierno haga espectaculares anuncios de corte progresista como el retiro de tropas argentinas de las Malvinas y el cierre del Penal de la Isla Martín García."
			+ "Entonces llegará el momento de la estocada final del plan elaborado por el “ala dura” del Obamismo norteamericano dela CIA de la casa Bñanca de Bush de Obama de la CIA de la Casa Blanca de los republicanos de George W. Bush de Obama: la fabricación de picos de loro gigantes para zurdos, que cumplirán la función de volver a girar los misiles nuevamente para el otro lado y así revitalizar la Industria siderírgica."
			+ "Entonces se revelará el verdadero objetivo de la Agenda estadounidense nortamericana de USA de EEUU de los US de los EU de Bush de Obama de Reagan repúblicanos de los halcones de las palomas del FBI de la derecha de la NRA de la agenda del “ala dura” de Obama de George W. Bush: la invasión de la argentina, a través de la excusa de salvar al pueblo norteamericano de la locura del denarvaizmo (ya que Francisco De narváez se volverá loco a los dos días de asumir, como se desprende observando sus ojillos de psicópata) que pretende instalartle un “mapa de la inseguridad” en el recto a los ciudadanos argentinos. ¿El objetivo oculto? Llevarse los meteoritos que abundan en Chaco, cuyo territorio habrá sido desmalezado y despoblado a través de la epidemia de dengue (que en realidad sería gripe porcina disfrazada, por lo que el uso de repelente sería totalmente inútil), con el objetivo de extraer su hierro para usos siderúrgicos con el fin de fabricar picos de loro gigantes para girar platarofrmas de misiles."
			+ "¿El fin? Vender el remanente de estas herramientas gigantes a los plomeros gigantes que serán requeridos en un par de meses para erreglar la termocupla y la electroválvula de las estufas instaladas en la Cordillera y utilizar ese dinero para palirar la Crisis Financiera. ";

	String longText6 = " ¡Lanzan Instructivo para encuentros en la calle!" + "Cosas para decir cuando se encuentran dos personas que llevan un bebé cada una:" + "-“¡Qué hermoso!”" + "-“¡Qué grande que está!”" + "-“Sí, es una bestia.”" + "-“Este come como un energúmeno.”" + "-“Es igual a vos, eh.”" + "-“Los ojos son de la madre.”" + "-“La nariz es de la madre.”" + "-“El pelo es de la madre.”" + "-“Las orejas son de la madre.”" + "-“¿Ya habla?”"
			+ "-“Sí, dice ‘aua’, ‘coméee’, ‘guau’ y ‘queo bajá’.”" + "-“El mío dice ‘plota’, ‘tita’, ‘añal’’, ‘alú’ y ‘omí’.”" + "-“¿Y ya camina?”" + "-“Sí, sí, no para, te agota”." + "-“El mío está ahi, está ahí.”" + "-¿Y te deja dormir?" + "-“Y, a veces, ja, ja, ja.”" + "-“El mío duerme toda la noche, como un angelito.”" + "-“No, el mío también, el mío también, eh.”" + "-“¿Y ya dejó el pañal?”" + "-“Le falta, le falta, está ahí, está ahí, es cosa de un par de días.”"
			+ "-“El mío también, está ahí, está ahí, yo creo que es cosa de menos de un día. Igual no lo quiero apurar porque estuvo mal de la panza y le está saliendo como una caca verde.”" + "-“Ah, al mío, también, la otra vez le salió como una caca verde. No te preocupes, no es nada.”" + "-“Chau, saludos, eh, está herrrrmoso, eh.”" + "-“El tuyo también, eh, herrrrrmoso, muy lindo, eh.”"
			+ "Cosas que no decir: “Epa, fulerita la criatura. Igual lo importante es que sea sanito.”, “¿NO CAMINA todavía? ¿Lo llevaste a un especialista? Te digo porque capaz que estás a tiempo”, “Yo no me quiero meter en cómo lo cuidás al pibe pero yo lo pondría a régimen”, etc." + "Cosas para decir cuando se encuentran dos personas que llevan un perro cada una:" + "-“¡Qué hermoso!”" + "-“¡Qué grande que está!”" + "-“Sí, es una bestia.”" + "-“Este come como un energúmeno.”"
			+ "-“¿Ya aprendió a hacer caca afuera?”" + "-“No, me deja cada regalito.”" + "-“Ah, el mío el otro día me dejó un tereso adentro del zapato. Lo-que-rí-a-ma-tar, ja, ja, ja.”" + "-“¿Ya ladra?”" + "-“¿Ya camina en cuatro patas?”" + "-“¿Y qué tipo de perro es?”" + "-“Es un Golden Retriever Daschund Airedale Pitbull terrier Shetland. Son re buenos con los chicos.”" + "-“Ah, igual hay que tener cuidado. El perro tiene que aprender su lugar en la casa.”"
			+ "-“Sí, el perro tiene que aprender su lugar en la casa. Por ejemplo, no lo dejamos más que se suba a la mesa a comer de nuestro plato.”" + "-“Sí.”" + "-“Y si te chumba, ¡cazote!”" + "-“Sí, yo le pego con un diario en la cola.”" + "-“Yo uso una barreta de hierro. Lo que pasa es que este tipo de perro no siente el dolor.”" + "-“El mío es un callejero, dicen que SON MÁS INTELIGENTES QUE LOS DE RAZA (mirando para otro lado, haciéndose el boludo).”"
			+ "-“Sí, bueno, cada perro tiene su personalidad. Lo bueno es que el perro de raza ya sabés cómo te viene. Lo otro es una lotería. Capaz que TE SALE UN PERRO ASESINO Y ES MEDIO UNA IRRESPONSABILIDAD TENERLO (mirando para otro lado, haciéndose el boludo).”" + "-“Sí, en fin, cada perro tiene su personalidad. Depende cómo lo eduques.”" + "-“Chau, saludos, eh, está herrrrmoso, eh.”" + "-“El tuyo también, eh, herrrrrmoso, muy lindo, eh.”"
			+ "Cosas que no decir: “Es igual a vos, eh”, “¿Vos PAGASTE por ese perro? ¿Con la cantidad de perritos abandonados que hay? Y buéh”, “Yo con mi plata hago lo que quiero, hijo de puta”." + "Cosas para decir cuando se encuentra una persona con un perro y una persona con un bebé:" + "-“¡Qué hermoso!”" + "-“¡Qué grande que está!”" + "-“Sí, es una bestia.”" + "-“Este come como un energúmeno.”" + "-“¿Y ya habla? Lo digo por el bebé.”" + "-“Sí, dice’ aua’, ‘coméee’, ‘guau’ y ‘queo bajá’.”"
			+ "-“¿Y el tuyo, ya ladra? Lo digo por el perro.”" + "-“Sí, dice ‘guau, guau, guau’”" + ". -“¿Y hace caca afuera? Lo digo por el perro.”" + "-“No, me hace cada enchastre, ja, ja, ja.”" + "-“¿Y todavía usa pañal? Lo digo por el bebé.”" + "-“Sí hace cada enchastre. Por suerte, adentro del pañal.”" + "-“¿Y ya camina? Lo digo por el bebé.”" + "-“El mío –que es un perro- ya camina. Y eso que tiene dos meses nada más.”" + "-“Claro, porque es un perro.”" + "-“Claro, claro, es otra cosa.”"
			+ "-“¿Y te deja dormir?”" + "-“Y, a veces lo tengo que pasar a la cama. Lo digo por el bebé.”" + "-“Y, a veces lo tengo que entrar. Lo digo por el perro. A la cama no, porque el perro tiene que saber su lugar, sino después te pasan por encima.”" + "-“Sí, sí, porque es un perro. El mío es un bebé.”" + "-“Sí, sí.”" + "-“No es lo mismo.”" + "-“No, claro, claro.”" + "-“¿Y tiene todas las vacunas?”" + "-“Le falta la del moquillo. Me refiero, claro, al perro.”"
			+ "-“A él le falta la Sabin. Me refiero, claro, al bebé.”" + "-“Se te re parece, eh. Me refiero, claro, al bebé.”" + "-“Sí. Él también se te re parece. Me refiero al perro. Porque dicen que los perros se parecen a sus dueños.”" + "-“Puede ser, puede ser, ja, ja. Es un Golden Retriever Daschund Airedale Pitbull Terrier Shetland. Son re buenos con los chicos.”" + "-“Él, directamente, es un chico.”" + "-“Sí.”" + "-“Lo importante es que no sea agresivo. Me refiero al perro.”"
			+ "-“Sí, depende cómo lo eduques. Me refiero al perro y también al bebé.”" + "-“Sí, pero no es lo mismo. Uno es un perro y el otro es un ser humano.”" + "-“Sí.”" + "-“Chau, saludos, eh, está herrrrmoso, eh.”" + "-“El tuyo también, eh, herrrrrmoso, muy lindo, eh.”"
			+ "Cosas que no decir: “Lo que yo no entiendo es cómo alguien puede traer un chico a este mundo lleno de Guerras y Desesperanza”, “Y a ver cuándo nos dejamos de joder con el perrito y tenés un hijo, mirá que se te va el tren, eh”, etc." + "Cosas para decir cuando se encuentra una persona con un bebé y una persona con un anciano:" + "-“¡Qué hermoso!”" + "-“¡Qué grande que está! Lo digo por el bebé”" + "-“¡Qué delgado, empequeñecido y enjuto que está! Lo digo por el anciano.”"
			+ "-“¿Y ya camina? Me refiero, claro, al bebé.”" + "-“¿Y todavía camina? Me refiero, claro, al anciano.”" + "-“¿Y todavía usa pañal? Me refiero, claro, al bebé.”" + "-“Y ya usa pañal? Me refiero, claro, al anciano.”" + "-“Le falta, le falta, es cosa de un par de días. Me refiero al bebé y también, desgraciadamente, al anciano”" + "-“¿Y te deja dormir?”" + "-“Y, a veces lo tengo que pasar a la cama. Estoy hablando del bebé.”"
			+ "-“Y, aveces le tengo que dar medio Lexotanil. Estoy hablando del anciano.”" + "-“¿Come papilla?" + "-“Sí.”" + "-“¿Y ya le salió algún diente? Lo digo por el bebé.”" + "-“¿Y le queda algún diente? Lo digo por el anciano.”" + "-“Es re parecido a vos, eh.”" + "-“Los ojos son de la madre, es decir, mi esposa. Me refiero al bebé.”" + "-“Los ojos son de la madre, es decir, mi bisabuela. Me refiero al anciano.”" + "-“¿Y cuánto tiempo tiene?”" + "-“Un año y medio. El bebé.”"
			+ "-“Ciento tres años. El anciano.”" + "-“Lo importante es que no sea agresivo. Me refiero al bebé y, por qué no, también al anciano.”" + "-“Depende cómo lo eduques. Me refiero al bebé.”" + "-“Depende de cómo esté de la cocorota. Me refiero al anciano.”" + "-“¿Y de la próstata cómo anda?”" + "-“¿El bebé o el anciano?”" + "-“No sé, cuál es el tuyo, el anciano?" + "-“Sí.”" + "-“Entonces, el anciano.”" + "-“Diez puntos.”"
			+ "-“El bebé también. Bah, el pediatra no dijo nada. Cuando no dice nada es porque está bien.”" + "-“Sí, cuando el gerontólogo no dice nada es porque también está bien.”" + "-“Chau, saludos, eh, está herrrrmoso, eh.”" + "-“El tuyo también, eh, herrrrrmoso, muy lindo, eh.”" + "Cosas que no decir: “¿Y cuánto le quedará? El anciano, digo”, “Y vos ahora hasta dentro de cuarenta añitos ni un minuto de tranquilidad, ¿no?”, etc."
			+ "Cosas para decir cuando se encuentra una persona con un perro, una persona con un bebé y una persona con un Golem:" + "-“¡Qué hermoso! Lo digo por el bebé y por el perro, no así por el Golem”" + "-“¡Qué grande que está! Lo digo por el bebé, el perro y el Golem.”" + "-“Sí, es una bestia (los tres).”" + "-“¿Y ya camina?”" + "-“Está ahí, está ahí. Lo digo por el bebé.”" + "-“Sí, ya camina, y eso que sólo tiene dos meses. Lo digo por el perro.”"
			+ "-“Sí, ya camina, y eso que sólo tiene unas Horas de habérsele dado el Don de la Animación. Lo digo por el Golem.”" + "-“¿Ya habla? Lo digo por el bebé y el Golem.”" + "-“Sí, dice ‘aua’, ‘coméee’, ‘guau’ y ‘queo bajá’. Me refiero, claro, al bebé.”" + "-“No, este es del tipo de Golems que no hablan. Me refiero, claro, al Golem.”" + "-“¿Y hace caca afuera?" + "-“¿Lo decís por el bebé, el perro o el Golem?”" + "-“Lo digo por los tres.”"
			+ "-“El perro aún no, el bebé no tiene por qué hacerlo y el Golem no hace caca de ningún tipo.”" + "-“Ah, OK.”" + "-“¿Y el tuyo obedece ciegamente todas y cada una de tus órdenes?”" + "-“¿Lo decís por el bebé, el perro o el Golem?”" + "-“Los tres.”" + "-“El perro no porque es cachorrito, el Golem sí y el bebé es un ser humano y debe ser educado en el uso responsable de la Libertad, no en la Obediencia Ciega.”" + "-“Ah, te creés que el bebé es mejor, ¿eh?"
			+ "-“Sí,es un ser humano. Es mejor.”" + "-(El del perro masculla con rabia)" + "-“¿Y el tuyo mata ante la orden de ‘¡Mata!’? Me refiero al bebé y al perro.”" + "-“No, es cachorrito. Me refiero al perro. Cuando crezca, veremos.”" + "-“No. Me refiero al bebé.”" + "-“El mío sí. Me refiero al Golem.”" + "-“Sí.”" + "-“En este punto en particular, ponele, el Golem es superior al bebé y en menor medida al perro.”" + "-“No es así, un ser humano es un ser humano.”"
			+ "-“Depende cómo lo eduques.”" + "-“No, no, no, yo privilegio al Humano. No vas a comparar con un animal y con un monigote horrible de barro.”" + "-“¡MATA! Me refiero, claro, al Golem.”" + "Cosas que no decir: “¿Y quién lo hizo al Golem este? ¿Un ciego?”, etc." + "Cosas para decir cuando se encuentra una persona con un perro, una persona con un bebé, una persona con una Estatua Viviente, una persona con una Avispa, una persona con Papá Noel y una persona con una persona."
			+ "-“¡Qué hermoso! Lo digo por el bebé, por el perro, la Estatua Viviente, la persona y en menor medida por la Avispa, porque los bichos me impresionan”" + "-“¡Qué grande que está! Ídem.”" + "-“¿Ya habla? Me refiero al bebé, no así a la Avispa, que no habla, ni a Papá Noel y a la persona, que ya deberían hablar desde hace tiempo, ni a la Estatua Viviente, que no debería hablar bajo ningún concepto.”" + "-“Sí, dice ‘aua’, ‘coméee’, ‘guau’ y ‘queo bajá’."
			+ "-“Bueno, mi Estatua Viviente a veces habla, pero por error.”" + "-“¿Y ya camina? Me refiero al bebé, no así a la Avispa, que no camina, ni a Papá Noel y a la persona, que ya deberían caminar desde hace tiempo, ni a la Estatua Viviente, que no debería caminar bajo ningún concepto.”" + "-“Sí, no para, es una máquina (el bebé).”" + "-“Una cosa, mi Estatua Viviente caminaba, cuando laburaba de Mimo. Pero no hablaba.”" + "-“Y la Avispa camina, ¡claro que camina! Tiene patas.”"
			+ "-“¿Y ya vuela? Me refiero a la Avispa, y en menor medida a Papá Noel, que no vuela per se.”" + "-“Sí, vuela. Lo digo por la Avispa.”" + "-“Sí, bueno, se puede decri que Papá Noel también vuela. No sé si per se, pero vuela.”" + "-“¿Y ya se recibió de abogada? Lo digo por la persona.”" + "-“No, pero es que no estudia para abogada.”" + "-“¿Y qué estudia?”" + "-“¿El perro, el bebé, la Estatua Viviente, la Avispa, papá Noel o la persona?” -“La persona, la persona.”" + "-“Ah, ah.”"
			+ "-“(Resopla) Veníamos hablando de la persona, ¿no? ¿De quién voy a hablar?”" + "-“Bueno, tranquilizate.”" + "-“¿Entonces al final qué estudia?”" + "-“No sé. Myriam, ¿qué estudiás?”" + "-“Fonoaudiología.”" + "-“¡Ah, HABLA la persona!”" + "-“Claro que habla, si dijimos que hablaba! Quedó claro que hablaba.”" + "-“Claro que hablo, hablo mejor que todos ustedes juntos, estudio fonoaudiología.”" + "-“Yo también hablo. Lo digo por mí, es decir, Papá Noel.”"
			+ "-“¡Ya sé! ¡Ya sabemos que Papá Noel habla!”" + "-“Pará, ¿ahora van a hablar las cosas que vienen con nosotros? Me refiero al bebé, el perro, la Avispa, la Estatua Viviente, Papá Noel y la persona. Porque si es así yo agarro y me voy. Lo digo yo, la persona que viene con el bebé.”" + "-“Aaaah, claro, el pibe se cree mejor que todos nosotros porque está con un bebé.”" + "-“Y sí, flaquito, es un ser humano, yo pongo al humano por encima de todo.”"
			+ "-“¡Pará! ¿Y la persona (Myriam)? También es una persona.”" + "-“¡MATA!”" + "-“Por qué lo decís? ¿Por el Golem? ¡Sí el Golem no estaba!!!!”" + "-“No, lo digo por Papá Noel. ¡MATA!”" + "-“Pará, loco. Y lo digo yo, que soy Papá Noel. Mirá que, antes que la obediencia ciega, yo he sido educado en la libertad con responsabilidad.”" + "-“Chau, saludos, eh, está herrrrmoso, eh.”" + "-“El tuyo también, eh, herrrrrmoso, muy lindo, eh.”" + "-(Esplota todo)"
			+ "Cosas que no decir: “Qué bebé más feo”, “Qué perro inmundo”, “Las estatuas vivientes apestan”, “Qué bicho de mierda la Avispa”, “Papá Noel no existe”, “La persona es boluda”, etc.";

}
